### ISSUE TITLE
Dual Sided cards don't work and crash the script

### ISSUE THREAD

**Issue by berndt-toast83** [ndepaola/mpc-scryfall#3]
When trying to pull a whole set or individual cards that contain dual side images, the script crashes. One card for example is Westvale Abbey. Here is the output from the script when trying to process that card:
Processing: Westvale Abbey
Traceback (most recent call last):
  File "C:\Users\bryan.berndt\Downloads\mpc-scryfall-master\scryfall_formatter.py", line 170, in <module>
    pipe_idx = cardname.index("|")
ValueError: substring not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\bryan.berndt\Downloads\mpc-scryfall-master\scryfall_formatter.py", line 173, in <module>
    process_card(cardname)
  File "C:\Users\bryan.berndt\Downloads\mpc-scryfall-master\scryfall_formatter.py", line 37, in process_card
    'image': card["image_uris"]['large'],
KeyError: 'image_uris'

The issue is that the JSON provided by the scryfall API doesn't have a image_uris node in the main card section, but rather it is nested under the card_faces node. It would be great if we can check if a card_faces node exists for a result and if so, process both image_uris and find a way to name them appropriately from the name node in the card_faces node.

Here is the full JSON for one of the dual sided cards:

{
    "object": "list",
    "total_cards": 1,
    "has_more": false,
    "data": [
        {
            "object": "card",
            "id": "c1f53d7a-9dad-46e8-b686-cd1362867445",
            "oracle_id": "04eeb9ad-5c59-411b-8809-db8349838588",
            "multiverse_ids": [
                410049,
                410050
            ],
            "mtgo_id": 59810,
            "mtgo_foil_id": 59811,
            "tcgplayer_id": 115917,
            "name": "Westvale Abbey // Ormendahl, Profane Prince",
            "lang": "en",
            "released_at": "2016-04-08",
            "uri": "https://api.scryfall.com/cards/c1f53d7a-9dad-46e8-b686-cd1362867445",
            "scryfall_uri": "https://scryfall.com/card/soi/281/westvale-abbey-ormendahl-profane-prince?utm_source=api",
            "layout": "transform",
            "highres_image": true,
            "cmc": 0.0,
            "type_line": "Land // Legendary Creature — Demon",
            "color_identity": [
                "B"
            ],
            "card_faces": [
                {
                    "object": "card_face",
                    "name": "Westvale Abbey",
                    "mana_cost": "",
                    "type_line": "Land",
                    "oracle_text": "{T}: Add {C}.\n{5}, {T}, Pay 1 life: Create a 1/1 white and black Human Cleric creature token.\n{5}, {T}, Sacrifice five creatures: Transform Westvale Abbey, then untap it.",
                    "colors": [],
                    "artist": "Min Yum",
                    "artist_id": "9cb65d6f-8851-4d56-9add-9eefa274bd1b",
                    "illustration_id": "6a0d5174-5a4d-406e-acd2-6c191f2a5cae",
                    "image_uris": {
                        "small": "https://img.scryfall.com/cards/small/front/c/1/c1f53d7a-9dad-46e8-b686-cd1362867445.jpg?1576385590",
                        "normal": "https://img.scryfall.com/cards/normal/front/c/1/c1f53d7a-9dad-46e8-b686-cd1362867445.jpg?1576385590",
                        "large": "https://img.scryfall.com/cards/large/front/c/1/c1f53d7a-9dad-46e8-b686-cd1362867445.jpg?1576385590",
                        "png": "https://img.scryfall.com/cards/png/front/c/1/c1f53d7a-9dad-46e8-b686-cd1362867445.png?1576385590",
                        "art_crop": "https://img.scryfall.com/cards/art_crop/front/c/1/c1f53d7a-9dad-46e8-b686-cd1362867445.jpg?1576385590",
                        "border_crop": "https://img.scryfall.com/cards/border_crop/front/c/1/c1f53d7a-9dad-46e8-b686-cd1362867445.jpg?1576385590"
                    }
                },
                {
                    "object": "card_face",
                    "name": "Ormendahl, Profane Prince",
                    "mana_cost": "",
                    "type_line": "Legendary Creature — Demon",
                    "oracle_text": "Flying, lifelink, indestructible, haste",
                    "colors": [
                        "B"
                    ],
                    "color_indicator": [
                        "B"
                    ],
                    "power": "9",
                    "toughness": "7",
                    "flavor_text": "With Griselbrand gone, the Skirsdag eagerly awaited another demon to claim their devotion. Ormendahl did not make them wait long.",
                    "artist": "Min Yum",
                    "artist_id": "9cb65d6f-8851-4d56-9add-9eefa274bd1b",
                    "illustration_id": "e576c60b-6928-4684-994f-ad80e127234b",
                    "image_uris": {
                        "small": "https://img.scryfall.com/cards/small/back/c/1/c1f53d7a-9dad-46e8-b686-cd1362867445.jpg?1576385590",
                        "normal": "https://img.scryfall.com/cards/normal/back/c/1/c1f53d7a-9dad-46e8-b686-cd1362867445.jpg?1576385590",
                        "large": "https://img.scryfall.com/cards/large/back/c/1/c1f53d7a-9dad-46e8-b686-cd1362867445.jpg?1576385590",
                        "png": "https://img.scryfall.com/cards/png/back/c/1/c1f53d7a-9dad-46e8-b686-cd1362867445.png?1576385590",
                        "art_crop": "https://img.scryfall.com/cards/art_crop/back/c/1/c1f53d7a-9dad-46e8-b686-cd1362867445.jpg?1576385590",
                        "border_crop": "https://img.scryfall.com/cards/border_crop/back/c/1/c1f53d7a-9dad-46e8-b686-cd1362867445.jpg?1576385590"
                    }
                }
            ],
            "all_parts": [
                {
                    "object": "related_card",
                    "id": "c1f53d7a-9dad-46e8-b686-cd1362867445",
                    "component": "combo_piece",
                    "name": "Westvale Abbey // Ormendahl, Profane Prince",
                    "type_line": "Land // Legendary Creature — Demon",
                    "uri": "https://api.scryfall.com/cards/c1f53d7a-9dad-46e8-b686-cd1362867445"
                },
                {
                    "object": "related_card",
                    "id": "94ed2eca-1579-411d-af6f-c7359c65de30",
                    "component": "token",
                    "name": "Human Cleric",
                    "type_line": "Token Creature — Human Cleric",
                    "uri": "https://api.scryfall.com/cards/94ed2eca-1579-411d-af6f-c7359c65de30"
                }
            ],
            "legalities": {
                "standard": "not_legal",
                "future": "not_legal",
                "historic": "not_legal",
                "pioneer": "legal",
                "modern": "legal",
                "legacy": "legal",
                "pauper": "not_legal",
                "vintage": "legal",
                "penny": "not_legal",
                "commander": "legal",
                "brawl": "not_legal",
                "duel": "legal",
                "oldschool": "not_legal"
            },
            "games": [
                "mtgo",
                "paper"
            ],
            "reserved": false,
            "foil": true,
            "nonfoil": true,
            "oversized": false,
            "promo": false,
            "reprint": false,
            "variation": false,
            "set": "soi",
            "set_name": "Shadows over Innistrad",
            "set_type": "expansion",
            "set_uri": "https://api.scryfall.com/sets/5e914d7e-c1e9-446c-a33d-d093c02b2743",
            "set_search_uri": "https://api.scryfall.com/cards/search?order=set&q=e%3Asoi&unique=prints",
            "scryfall_set_uri": "https://scryfall.com/sets/soi?utm_source=api",
            "rulings_uri": "https://api.scryfall.com/cards/c1f53d7a-9dad-46e8-b686-cd1362867445/rulings",
            "prints_search_uri": "https://api.scryfall.com/cards/search?order=released&q=oracleid%3A04eeb9ad-5c59-411b-8809-db8349838588&unique=prints",
            "collector_number": "281",
            "digital": false,
            "rarity": "rare",
            "card_back_id": "0aeebaf5-8c7d-4636-9e82-8c27447861f7",
            "artist": "Min Yum",
            "artist_ids": [
                "9cb65d6f-8851-4d56-9add-9eefa274bd1b"
            ],
            "border_color": "black",
            "frame": "2015",
            "frame_effects": [
                "sunmoondfc"
            ],
            "full_art": false,
            "textless": false,
            "booster": true,
            "story_spotlight": false,
            "edhrec_rank": 379,
            "prices": {
                "usd": "5.58",
                "usd_foil": "8.10",
                "eur": "4.01",
                "tix": "0.67"
            },
            "related_uris": {
                "gatherer": "https://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=410049",
                "tcgplayer_decks": "https://decks.tcgplayer.com/magic/deck/search?contains=Westvale+Abbey&page=1&partner=Scryfall&utm_campaign=affiliate&utm_medium=scryfall&utm_source=scryfall",
                "edhrec": "https://edhrec.com/route/?cc=Westvale+Abbey",
                "mtgtop8": "https://mtgtop8.com/search?MD_check=1&SB_check=1&cards=Westvale+Abbey"
            },
            "purchase_uris": {
                "tcgplayer": "https://shop.tcgplayer.com/product/productsearch?id=115917&partner=Scryfall&utm_campaign=affiliate&utm_medium=scryfall&utm_source=scryfall",
                "cardmarket": "https://www.cardmarket.com/en/Magic/Products/Singles/Shadows-over-Innistrad/Westvale-Abbey-Ormendahl-Profane-Prince?referrer=scryfall&utm_campaign=card_prices&utm_medium=text&utm_source=scryfall",
                "cardhoarder": "https://www.cardhoarder.com/cards/59810?affiliate_id=scryfall&ref=card-profile&utm_campaign=affiliate&utm_medium=card&utm_source=scryfall"
            }
        }
    ]
}

**Comment by berndt-toast83** [comment]
I've gotten it to download the correct images based on the image_uris array, but my python knowledge is not high at all. I'm sure this can be done with a for loop, but here is what I added/changed to make it work:

`def extract_values(obj, key):
    """Pull all values of specified key from nested JSON."""
    arr = []

    def extract(obj, arr, key):
        """Recursively search for values of key in JSON tree."""
        if isinstance(obj, dict):
            for k, v in obj.items():
                if isinstance(v, (dict, list)):
                    extract(v, arr, key)
                elif k == key:
                    arr.append(v)
        elif isinstance(obj, list):
            for item in obj:
                extract(item, arr, key)
        return arr

    results = extract(obj, arr, key)
    return results


def process_card(cardname, expansion=None):
    time.sleep(0.05)

    # try/except in case the search doesn't return anything
    try:
        # If the card specifies which set to retrieve the scan from, do that
        if expansion:
            # Set specified from set formatter
            query = "!\"" + cardname + "\" set=" + expansion
            print("Processing: " + cardname + ", set: " + expansion)
        else:
            query = "!\"" + cardname + "\""
            print("Processing: " + cardname)
        card = scrython.cards.Search(q=query).data()[0]

    except scrython.foundation.ScryfallError:
        print("Couldn't find card: " + cardname)
        return

    cardname = card["name"].replace("//", "&")  # should work on macOS & windows now
    cardname = cardname.replace(":", "")  # case for Circle of Protection: X

    # process with waifu2x
    image_uris = extract_values(card, 'large')
    print(image_uris)
    name = extract_values(card, 'name')
    print(name)
    try:
        if len(image_uris)==2:
            r = requests.post(
                "https://api.deepai.org/api/waifu2x",
                data={
                    'image': image_uris[1],
                },
                headers={'api-key': config.TOKEN}
            )
            output_url = r.json()['output_url']
            im = imageio.imread(output_url)
        else:
            r = requests.post(
                "https://api.deepai.org/api/waifu2x",
                data={
                    'image': card["image_uris"]['large'],
                },
                headers={'api-key': config.TOKEN}
            )
            output_url = r.json()['output_url']
            im = imageio.imread(output_url)
            
    except:
        print("Continue")
        return`

**Comment by berndt-toast83** [comment]
I've gotten it to download the individual image for each side, but my knowledge of python formatting is not good at all, so need your help getting this to work. Adding a for loop in the case where len(image_uris)==2 should allow us to get both image uris for both sides.

def extract_values(obj, key):
    """Pull all values of specified key from nested JSON."""
    arr = []

    def extract(obj, arr, key):
        """Recursively search for values of key in JSON tree."""
        if isinstance(obj, dict):
            for k, v in obj.items():
                if isinstance(v, (dict, list)):
                    extract(v, arr, key)
                elif k == key:
                    arr.append(v)
        elif isinstance(obj, list):
            for item in obj:
                extract(item, arr, key)
        return arr

    results = extract(obj, arr, key)
    return results


def process_card(cardname, expansion=None):
    time.sleep(0.05)

    # try/except in case the search doesn't return anything
    try:
        # If the card specifies which set to retrieve the scan from, do that
        if expansion:
            # Set specified from set formatter
            query = "!\"" + cardname + "\" set=" + expansion
            print("Processing: " + cardname + ", set: " + expansion)
        else:
            query = "!\"" + cardname + "\""
            print("Processing: " + cardname)
        card = scrython.cards.Search(q=query).data()[0]

    except scrython.foundation.ScryfallError:
        print("Couldn't find card: " + cardname)
        return

    cardname = card["name"].replace("//", "&")  # should work on macOS & windows now
    cardname = cardname.replace(":", "")  # case for Circle of Protection: X

    # process with waifu2x
    image_uris = extract_values(card, 'large')
    print(image_uris)
    name = extract_values(card, 'name')
    print(name)
    try:
        if len(image_uris)==2:
            r = requests.post(
                "https://api.deepai.org/api/waifu2x",
                data={
                    'image': image_uris[1],
                },
                headers={'api-key': config.TOKEN}
            )
            output_url = r.json()['output_url']
            im = imageio.imread(output_url)
        else:
            r = requests.post(
                "https://api.deepai.org/api/waifu2x",
                data={
                    'image': card["image_uris"]['large'],
                },
                headers={'api-key': config.TOKEN}
            )
            output_url = r.json()['output_url']
            im = imageio.imread(output_url)
            
    except:
        print("Continue")
        return

**Comment by ndepaola** [comment]
hey, sorry for the delay on this - I added support for DFC's in the latest commit. If you give it the name of either side, it'll do both sides for you. Let me know if you have any issues with it then I'll close this issue :)

**Comment by berndt-toast83** [comment]
Looks good, good to close.
